// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2dpRdrBgiPImQO4LQ7km7EcWgoZWAuI',
    appId: '1:392830913223:android:82a7bfc43999ceba744ce2',
    messagingSenderId: '392830913223',
    projectId: 'alura-flutter-crashlytic-29e56',
    storageBucket: 'alura-flutter-crashlytic-29e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7y76tXPsDNzr8Fimft16iws0ixbKeSY',
    appId: '1:392830913223:ios:75adb83c661a134f744ce2',
    messagingSenderId: '392830913223',
    projectId: 'alura-flutter-crashlytic-29e56',
    storageBucket: 'alura-flutter-crashlytic-29e56.appspot.com',
    iosClientId:
        '392830913223-aadcb36m0bd44kjkfqui2r0hus14gpfn.apps.googleusercontent.com',
    iosBundleId: 'com.murilovsky.bytebank',
  );
}
